# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HookCollectionView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HookCollectionView(object):
    def setupUi(self, HookCollectionView):
        HookCollectionView.setObjectName(_fromUtf8("HookCollectionView"))
        HookCollectionView.resize(1756, 1203)
        self.hookCollectionView = QtGui.QWidget(HookCollectionView)
        self.hookCollectionView.setObjectName(_fromUtf8("hookCollectionView"))
        self.hookCollectionButton = QtGui.QPushButton(self.hookCollectionView)
        self.hookCollectionButton.setGeometry(QtCore.QRect(30, 20, 241, 51))
        self.hookCollectionButton.setObjectName(_fromUtf8("hookCollectionButton"))
        self.editButton = QtGui.QPushButton(self.hookCollectionView)
        self.editButton.setGeometry(QtCore.QRect(290, 20, 241, 51))
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.deleteButton = QtGui.QPushButton(self.hookCollectionView)
        self.deleteButton.setGeometry(QtCore.QRect(550, 20, 241, 51))
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.textBoxLabeledAsSearch = QtGui.QTextEdit(self.hookCollectionView)
        self.textBoxLabeledAsSearch.setGeometry(QtCore.QRect(1260, 20, 381, 51))
        self.textBoxLabeledAsSearch.setObjectName(_fromUtf8("textBoxLabeledAsSearch"))
        self.searchLabel = QtGui.QLabel(self.hookCollectionView)
        self.searchLabel.setGeometry(QtCore.QRect(1180, 30, 103, 29))
        self.searchLabel.setObjectName(_fromUtf8("searchLabel"))
        self.pageLabel = QtGui.QLabel(self.hookCollectionView)
        self.pageLabel.setGeometry(QtCore.QRect(700, 1070, 103, 29))
        self.pageLabel.setObjectName(_fromUtf8("pageLabel"))
        self.hookCollectionPropertiesTable = QtGui.QTableWidget(self.hookCollectionView)
        self.hookCollectionPropertiesTable.setGeometry(QtCore.QRect(80, 140, 1611, 911))
        self.hookCollectionPropertiesTable.setMinimumSize(QtCore.QSize(1611, 911))
        self.hookCollectionPropertiesTable.setAutoFillBackground(False)
        self.hookCollectionPropertiesTable.setRowCount(7)
        self.hookCollectionPropertiesTable.setColumnCount(5)
        self.hookCollectionPropertiesTable.setObjectName(_fromUtf8("hookCollectionPropertiesTable"))
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.hookCollectionPropertiesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookCollectionPropertiesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookCollectionPropertiesTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookCollectionPropertiesTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookCollectionPropertiesTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hookCollectionPropertiesTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.hookCollectionPropertiesTable.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.hookCollectionPropertiesTable.setItem(6, 4, item)
        self.hookCollectionPropertiesTable.horizontalHeader().setVisible(True)
        self.hookCollectionPropertiesTable.horizontalHeader().setCascadingSectionResizes(False)
        self.hookCollectionPropertiesTable.horizontalHeader().setDefaultSectionSize(315)
        self.hookCollectionPropertiesTable.horizontalHeader().setSortIndicatorShown(True)
        self.radioButton = QtGui.QRadioButton(self.hookCollectionView)
        self.radioButton.setGeometry(QtCore.QRect(240, 220, 171, 33))
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.hookCollectionView)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 610, 171, 33))
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.page1button = QtGui.QPushButton(self.hookCollectionView)
        self.page1button.setGeometry(QtCore.QRect(760, 1060, 31, 51))
        self.page1button.setObjectName(_fromUtf8("page1button"))
        self.pageNumSplit = QtGui.QLabel(self.hookCollectionView)
        self.pageNumSplit.setGeometry(QtCore.QRect(800, 1070, 21, 29))
        self.pageNumSplit.setObjectName(_fromUtf8("pageNumSplit"))
        self.page2button = QtGui.QPushButton(self.hookCollectionView)
        self.page2button.setGeometry(QtCore.QRect(820, 1060, 31, 51))
        self.page2button.setObjectName(_fromUtf8("page2button"))
        self.pageNumSplit_2 = QtGui.QLabel(self.hookCollectionView)
        self.pageNumSplit_2.setGeometry(QtCore.QRect(860, 1070, 21, 29))
        self.pageNumSplit_2.setObjectName(_fromUtf8("pageNumSplit_2"))
        self.pushButton = QtGui.QPushButton(self.hookCollectionView)
        self.pushButton.setGeometry(QtCore.QRect(880, 1060, 31, 51))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pageNumSplit_3 = QtGui.QLabel(self.hookCollectionView)
        self.pageNumSplit_3.setGeometry(QtCore.QRect(920, 1070, 61, 29))
        self.pageNumSplit_3.setObjectName(_fromUtf8("pageNumSplit_3"))
        self.hookCollectionPropertiesLabel = QtGui.QLabel(self.hookCollectionView)
        self.hookCollectionPropertiesLabel.setGeometry(QtCore.QRect(80, 80, 1611, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hookCollectionPropertiesLabel.setFont(font)
        self.hookCollectionPropertiesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hookCollectionPropertiesLabel.setObjectName(_fromUtf8("hookCollectionPropertiesLabel"))
        self.toolButton = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton.setGeometry(QtCore.QRect(690, 140, 31, 31))
        self.toolButton.setText(_fromUtf8(""))
        self.toolButton.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_5 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_5.setGeometry(QtCore.QRect(690, 170, 31, 31))
        self.toolButton_5.setText(_fromUtf8(""))
        self.toolButton_5.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.toolButton_2 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_2.setGeometry(QtCore.QRect(1010, 140, 31, 31))
        self.toolButton_2.setText(_fromUtf8(""))
        self.toolButton_2.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.toolButton_3 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_3.setGeometry(QtCore.QRect(1320, 140, 31, 31))
        self.toolButton_3.setText(_fromUtf8(""))
        self.toolButton_3.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.toolButton_4 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_4.setGeometry(QtCore.QRect(1640, 140, 31, 31))
        self.toolButton_4.setText(_fromUtf8(""))
        self.toolButton_4.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.toolButton_6 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_6.setGeometry(QtCore.QRect(1010, 170, 31, 31))
        self.toolButton_6.setText(_fromUtf8(""))
        self.toolButton_6.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.toolButton_7 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_7.setGeometry(QtCore.QRect(1320, 170, 31, 31))
        self.toolButton_7.setText(_fromUtf8(""))
        self.toolButton_7.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.toolButton_8 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_8.setGeometry(QtCore.QRect(1640, 170, 31, 31))
        self.toolButton_8.setText(_fromUtf8(""))
        self.toolButton_8.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.toolButton_9 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_9.setGeometry(QtCore.QRect(420, 220, 31, 31))
        self.toolButton_9.setText(_fromUtf8(""))
        self.toolButton_9.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.toolButton_10 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_10.setGeometry(QtCore.QRect(420, 620, 31, 31))
        self.toolButton_10.setText(_fromUtf8(""))
        self.toolButton_10.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.label = QtGui.QLabel(self.hookCollectionView)
        self.label.setGeometry(QtCore.QRect(420, 260, 1261, 71))
        self.label.setObjectName(_fromUtf8("label"))
        self.hookTableOfTheHookCollectionsPropertiesTable = QtGui.QTableWidget(self.hookCollectionView)
        self.hookTableOfTheHookCollectionsPropertiesTable.setGeometry(QtCore.QRect(415, 331, 1261, 261))
        self.hookTableOfTheHookCollectionsPropertiesTable.setObjectName(_fromUtf8("hookTableOfTheHookCollectionsPropertiesTable"))
        self.hookTableOfTheHookCollectionsPropertiesTable.setColumnCount(4)
        self.hookTableOfTheHookCollectionsPropertiesTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookTableOfTheHookCollectionsPropertiesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookTableOfTheHookCollectionsPropertiesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookTableOfTheHookCollectionsPropertiesTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.hookTableOfTheHookCollectionsPropertiesTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.hookTableOfTheHookCollectionsPropertiesTable.setItem(2, 3, item)
        self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeader().setVisible(True)
        self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeader().setDefaultSectionSize(310)
        self.hookTableOfTheHookCollectionsPropertiesTable.verticalHeader().setVisible(False)
        self.toolButton_11 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_11.setGeometry(QtCore.QRect(690, 330, 31, 31))
        self.toolButton_11.setText(_fromUtf8(""))
        self.toolButton_11.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.toolButton_12 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_12.setGeometry(QtCore.QRect(1000, 330, 31, 31))
        self.toolButton_12.setText(_fromUtf8(""))
        self.toolButton_12.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.toolButton_13 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_13.setGeometry(QtCore.QRect(1310, 330, 31, 31))
        self.toolButton_13.setText(_fromUtf8(""))
        self.toolButton_13.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.toolButton_14 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_14.setGeometry(QtCore.QRect(1630, 330, 31, 31))
        self.toolButton_14.setText(_fromUtf8(""))
        self.toolButton_14.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.toolButton_15 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_15.setGeometry(QtCore.QRect(690, 360, 31, 31))
        self.toolButton_15.setText(_fromUtf8(""))
        self.toolButton_15.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_15.setObjectName(_fromUtf8("toolButton_15"))
        self.toolButton_16 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_16.setGeometry(QtCore.QRect(1000, 360, 31, 31))
        self.toolButton_16.setText(_fromUtf8(""))
        self.toolButton_16.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_16.setObjectName(_fromUtf8("toolButton_16"))
        self.toolButton_17 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_17.setGeometry(QtCore.QRect(1310, 360, 31, 31))
        self.toolButton_17.setText(_fromUtf8(""))
        self.toolButton_17.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_17.setObjectName(_fromUtf8("toolButton_17"))
        self.toolButton_18 = QtGui.QToolButton(self.hookCollectionView)
        self.toolButton_18.setGeometry(QtCore.QRect(1630, 360, 31, 31))
        self.toolButton_18.setText(_fromUtf8(""))
        self.toolButton_18.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton_18.setObjectName(_fromUtf8("toolButton_18"))
        HookCollectionView.setCentralWidget(self.hookCollectionView)
        self.menubar = QtGui.QMenuBar(HookCollectionView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1756, 43))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        HookCollectionView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(HookCollectionView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        HookCollectionView.setStatusBar(self.statusbar)

        self.retranslateUi(HookCollectionView)
        QtCore.QMetaObject.connectSlotsByName(HookCollectionView)

    def retranslateUi(self, HookCollectionView):
        HookCollectionView.setWindowTitle(_translate("HookCollectionView", "MainWindow", None))
        self.hookCollectionButton.setText(_translate("HookCollectionView", "+ Hook Collection", None))
        self.editButton.setText(_translate("HookCollectionView", "Edit", None))
        self.deleteButton.setText(_translate("HookCollectionView", "Delete", None))
        self.searchLabel.setText(_translate("HookCollectionView", "Search", None))
        self.pageLabel.setText(_translate("HookCollectionView", "Page:", None))
        self.hookCollectionPropertiesTable.setSortingEnabled(True)
        item = self.hookCollectionPropertiesTable.horizontalHeaderItem(1)
        item.setText(_translate("HookCollectionView", "Hook Collection", None))
        item = self.hookCollectionPropertiesTable.horizontalHeaderItem(2)
        item.setText(_translate("HookCollectionView", "No. of Hooks", None))
        item = self.hookCollectionPropertiesTable.horizontalHeaderItem(3)
        item.setText(_translate("HookCollectionView", "Hook Collection Status", None))
        item = self.hookCollectionPropertiesTable.horizontalHeaderItem(4)
        item.setText(_translate("HookCollectionView", "Hook Collection Execution Sequence", None))
        __sortingEnabled = self.hookCollectionPropertiesTable.isSortingEnabled()
        self.hookCollectionPropertiesTable.setSortingEnabled(False)
        item = self.hookCollectionPropertiesTable.item(0, 1)
        item.setText(_translate("HookCollectionView", "Hook Collection 1", None))
        item = self.hookCollectionPropertiesTable.item(0, 2)
        item.setText(_translate("HookCollectionView", "2", None))
        item = self.hookCollectionPropertiesTable.item(0, 3)
        item.setText(_translate("HookCollectionView", "Enabled", None))
        item = self.hookCollectionPropertiesTable.item(0, 4)
        item.setText(_translate("HookCollectionView", "1", None))
        item = self.hookCollectionPropertiesTable.item(6, 1)
        item.setText(_translate("HookCollectionView", "Hook Collection 2", None))
        item = self.hookCollectionPropertiesTable.item(6, 2)
        item.setText(_translate("HookCollectionView", "0", None))
        item = self.hookCollectionPropertiesTable.item(6, 3)
        item.setText(_translate("HookCollectionView", "Disabled", None))
        item = self.hookCollectionPropertiesTable.item(6, 4)
        item.setText(_translate("HookCollectionView", "3", None))
        self.hookCollectionPropertiesTable.setSortingEnabled(__sortingEnabled)
        self.page1button.setText(_translate("HookCollectionView", "1", None))
        self.pageNumSplit.setText(_translate("HookCollectionView", "|", None))
        self.page2button.setText(_translate("HookCollectionView", "2", None))
        self.pageNumSplit_2.setText(_translate("HookCollectionView", "|", None))
        self.pushButton.setText(_translate("HookCollectionView", "3", None))
        self.pageNumSplit_3.setText(_translate("HookCollectionView", "| ...", None))
        self.hookCollectionPropertiesLabel.setText(_translate("HookCollectionView", "Hook Collection Properties", None))
        self.label.setText(_translate("HookCollectionView", "Description:", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.verticalHeaderItem(0)
        item.setText(_translate("HookCollectionView", "New Row", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.verticalHeaderItem(1)
        item.setText(_translate("HookCollectionView", "New Row", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.verticalHeaderItem(2)
        item.setText(_translate("HookCollectionView", "New Row", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeaderItem(0)
        item.setText(_translate("HookCollectionView", "Hook", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeaderItem(1)
        item.setText(_translate("HookCollectionView", "Description", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeaderItem(2)
        item.setText(_translate("HookCollectionView", "Hook Status", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.horizontalHeaderItem(3)
        item.setText(_translate("HookCollectionView", "Hook Execution Sequence", None))
        __sortingEnabled = self.hookTableOfTheHookCollectionsPropertiesTable.isSortingEnabled()
        self.hookTableOfTheHookCollectionsPropertiesTable.setSortingEnabled(False)
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(0, 0)
        item.setText(_translate("HookCollectionView", "Hook 1", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(0, 1)
        item.setText(_translate("HookCollectionView", "Description 1", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(0, 2)
        item.setText(_translate("HookCollectionView", "Enabled", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(0, 3)
        item.setText(_translate("HookCollectionView", "2", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(1, 0)
        item.setText(_translate("HookCollectionView", "Hook 3", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(1, 1)
        item.setText(_translate("HookCollectionView", "Description 3", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(1, 2)
        item.setText(_translate("HookCollectionView", "Disabled", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(1, 3)
        item.setText(_translate("HookCollectionView", "1", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(2, 0)
        item.setText(_translate("HookCollectionView", "Hook 4", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(2, 1)
        item.setText(_translate("HookCollectionView", "Description 4", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(2, 2)
        item.setText(_translate("HookCollectionView", "Enabled", None))
        item = self.hookTableOfTheHookCollectionsPropertiesTable.item(2, 3)
        item.setText(_translate("HookCollectionView", "3", None))
        self.hookTableOfTheHookCollectionsPropertiesTable.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    HookCollectionView = QtGui.QMainWindow()
    ui = Ui_HookCollectionView()
    ui.setupUi(HookCollectionView)
    HookCollectionView.show()
    sys.exit(app.exec_())

