# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NTPS.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1396, 839)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.OptionView = QtGui.QGroupBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.OptionView.setPalette(palette)
        self.OptionView.setAutoFillBackground(False)
        self.OptionView.setFlat(False)
        self.OptionView.setCheckable(False)
        self.OptionView.setObjectName(_fromUtf8("OptionView"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OptionView)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.HookCollectionButton = QtGui.QPushButton(self.OptionView)
        self.HookCollectionButton.setObjectName(_fromUtf8("HookCollectionButton"))
        self.gridLayout_2.addWidget(self.HookCollectionButton, 1, 0, 1, 1)
        self.LivePacketButton = QtGui.QPushButton(self.OptionView)
        self.LivePacketButton.setObjectName(_fromUtf8("LivePacketButton"))
        self.gridLayout_2.addWidget(self.LivePacketButton, 2, 0, 1, 1)
        self.HookButton = QtGui.QPushButton(self.OptionView)
        self.HookButton.setEnabled(True)
        self.HookButton.setCheckable(False)
        self.HookButton.setObjectName(_fromUtf8("HookButton"))
        self.gridLayout_2.addWidget(self.HookButton, 0, 0, 1, 1)
        self.PCAPPacketButton = QtGui.QPushButton(self.OptionView)
        self.PCAPPacketButton.setObjectName(_fromUtf8("PCAPPacketButton"))
        self.gridLayout_2.addWidget(self.PCAPPacketButton, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.OptionView, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.stackedWidgetPage1 = QtGui.QWidget()
        self.stackedWidgetPage1.setObjectName(_fromUtf8("stackedWidgetPage1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.stackedWidgetPage1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.DeleteHook = QtGui.QPushButton(self.stackedWidgetPage1)
        self.DeleteHook.setObjectName(_fromUtf8("DeleteHook"))
        self.gridLayout_3.addWidget(self.DeleteHook, 0, 2, 1, 1)
        self.EditHook = QtGui.QPushButton(self.stackedWidgetPage1)
        self.EditHook.setObjectName(_fromUtf8("EditHook"))
        self.gridLayout_3.addWidget(self.EditHook, 0, 1, 1, 1)
        self.SearchHook = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.SearchHook.setObjectName(_fromUtf8("SearchHook"))
        self.gridLayout_3.addWidget(self.SearchHook, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.stackedWidgetPage1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 4, 1, 1)
        self.AddHook = QtGui.QPushButton(self.stackedWidgetPage1)
        self.AddHook.setObjectName(_fromUtf8("AddHook"))
        self.gridLayout_3.addWidget(self.AddHook, 0, 0, 1, 1)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.stackedWidgetPage1)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.page_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 4)
        self.radioButton = QtGui.QRadioButton(self.page_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_4.addWidget(self.radioButton, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.page_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 2, 1, 1, 4)
        self.line_3 = QtGui.QFrame(self.page_3)
        self.line_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.line_3.setAutoFillBackground(True)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 14, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 5, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 7, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 6, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.page_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 8, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 11, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.page_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 10, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 13, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 9, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 12, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 4, 1, 1)
        self.line_4 = QtGui.QFrame(self.page_3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_4.addWidget(self.line_4, 1, 5, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stackedWidget_2.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 1, 0, 1, 6)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtGui.QWidget()
        self.stackedWidgetPage2.setObjectName(_fromUtf8("stackedWidgetPage2"))
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1396, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.HookButton, self.HookCollectionButton)
        MainWindow.setTabOrder(self.HookCollectionButton, self.LivePacketButton)
        MainWindow.setTabOrder(self.LivePacketButton, self.PCAPPacketButton)
        MainWindow.setTabOrder(self.PCAPPacketButton, self.AddHook)
        MainWindow.setTabOrder(self.AddHook, self.EditHook)
        MainWindow.setTabOrder(self.EditHook, self.DeleteHook)
        MainWindow.setTabOrder(self.DeleteHook, self.SearchHook)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.OptionView.setTitle(_translate("MainWindow", "Option View", None))
        self.HookCollectionButton.setText(_translate("MainWindow", "Hook Collection", None))
        self.LivePacketButton.setText(_translate("MainWindow", "Live Packet", None))
        self.HookButton.setText(_translate("MainWindow", "Hook", None))
        self.PCAPPacketButton.setText(_translate("MainWindow", "Packet from PCAP", None))
        self.DeleteHook.setText(_translate("MainWindow", "Delete", None))
        self.EditHook.setText(_translate("MainWindow", "Edit", None))
        self.label.setText(_translate("MainWindow", "Search", None))
        self.AddHook.setText(_translate("MainWindow", "+Hook", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.radioButton.setText(_translate("MainWindow", "RadioButton", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.label_14.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "Description", None))
        self.label_3.setText(_translate("MainWindow", "Hook", None))
        self.label_2.setText(_translate("MainWindow", "Association to Hook Collection", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

