# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1462, 875)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.OptionView = QtGui.QGroupBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.OptionView.setPalette(palette)
        self.OptionView.setAutoFillBackground(False)
        self.OptionView.setFlat(False)
        self.OptionView.setCheckable(False)
        self.OptionView.setObjectName(_fromUtf8("OptionView"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OptionView)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.HookCollectionButton = QtGui.QPushButton(self.OptionView)
        self.HookCollectionButton.setObjectName(_fromUtf8("HookCollectionButton"))
        self.gridLayout_2.addWidget(self.HookCollectionButton, 1, 0, 1, 1)
        self.LivePacketButton = QtGui.QPushButton(self.OptionView)
        self.LivePacketButton.setObjectName(_fromUtf8("LivePacketButton"))
        self.gridLayout_2.addWidget(self.LivePacketButton, 2, 0, 1, 1)
        self.PCAPPacketButton = QtGui.QPushButton(self.OptionView)
        self.PCAPPacketButton.setObjectName(_fromUtf8("PCAPPacketButton"))
        self.gridLayout_2.addWidget(self.PCAPPacketButton, 3, 0, 1, 1)
        self.HookButton = QtGui.QPushButton(self.OptionView)
        self.HookButton.setEnabled(True)
        self.HookButton.setCheckable(False)
        self.HookButton.setObjectName(_fromUtf8("HookButton"))
        self.gridLayout_2.addWidget(self.HookButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.OptionView, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.HookView = QtGui.QWidget()
        self.HookView.setObjectName(_fromUtf8("HookView"))
        self.gridLayout_3 = QtGui.QGridLayout(self.HookView)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.DeleteHook = QtGui.QPushButton(self.HookView)
        self.DeleteHook.setObjectName(_fromUtf8("DeleteHook"))
        self.gridLayout_3.addWidget(self.DeleteHook, 0, 2, 1, 1)
        self.EditHook = QtGui.QPushButton(self.HookView)
        self.EditHook.setObjectName(_fromUtf8("EditHook"))
        self.gridLayout_3.addWidget(self.EditHook, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.HookView)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 4, 1, 1)
        self.SearchHook = QtGui.QLineEdit(self.HookView)
        self.SearchHook.setObjectName(_fromUtf8("SearchHook"))
        self.gridLayout_3.addWidget(self.SearchHook, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.AddHook = QtGui.QPushButton(self.HookView)
        self.AddHook.setObjectName(_fromUtf8("AddHook"))
        self.gridLayout_3.addWidget(self.AddHook, 0, 0, 1, 1)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.HookView)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.line = QtGui.QFrame(self.page_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 4)
        self.line_2 = QtGui.QFrame(self.page_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 2, 1, 1, 4)
        self.line_3 = QtGui.QFrame(self.page_3)
        self.line_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.line_3.setAutoFillBackground(True)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.page_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_4.addWidget(self.radioButton, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 23, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.page_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 8, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 22, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 6, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 9, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 4, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.page_3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_4.addWidget(self.line_4, 1, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 5, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 20, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 7, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.page_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 19, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 21, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.page_3)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_4.addWidget(self.radioButton_3, 5, 0, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.page_3)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout_4.addWidget(self.radioButton_5, 7, 0, 1, 1)
        self.radioButton_9 = QtGui.QRadioButton(self.page_3)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.gridLayout_4.addWidget(self.radioButton_9, 20, 0, 1, 1)
        self.radioButton_8 = QtGui.QRadioButton(self.page_3)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.gridLayout_4.addWidget(self.radioButton_8, 19, 0, 1, 1)
        self.radioButton_11 = QtGui.QRadioButton(self.page_3)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.gridLayout_4.addWidget(self.radioButton_11, 22, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.page_3)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_4.addWidget(self.radioButton_2, 4, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.page_3)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_4.addWidget(self.radioButton_4, 6, 0, 1, 1)
        self.radioButton_7 = QtGui.QRadioButton(self.page_3)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.gridLayout_4.addWidget(self.radioButton_7, 9, 0, 1, 1)
        self.radioButton_6 = QtGui.QRadioButton(self.page_3)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.gridLayout_4.addWidget(self.radioButton_6, 8, 0, 1, 1)
        self.radioButton_17 = QtGui.QRadioButton(self.page_3)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.gridLayout_4.addWidget(self.radioButton_17, 11, 0, 1, 1)
        self.radioButton_19 = QtGui.QRadioButton(self.page_3)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.gridLayout_4.addWidget(self.radioButton_19, 15, 0, 1, 1)
        self.radioButton_20 = QtGui.QRadioButton(self.page_3)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.gridLayout_4.addWidget(self.radioButton_20, 17, 0, 1, 1)
        self.radioButton_18 = QtGui.QRadioButton(self.page_3)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.gridLayout_4.addWidget(self.radioButton_18, 13, 0, 1, 1)
        self.radioButton_22 = QtGui.QRadioButton(self.page_3)
        self.radioButton_22.setObjectName(_fromUtf8("radioButton_22"))
        self.gridLayout_4.addWidget(self.radioButton_22, 12, 0, 1, 1)
        self.radioButton_10 = QtGui.QRadioButton(self.page_3)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.gridLayout_4.addWidget(self.radioButton_10, 21, 0, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.page_3)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.gridLayout_4.addWidget(self.radioButton_15, 10, 0, 1, 1)
        self.radioButton_16 = QtGui.QRadioButton(self.page_3)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.gridLayout_4.addWidget(self.radioButton_16, 18, 0, 1, 1)
        self.radioButton_14 = QtGui.QRadioButton(self.page_3)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.gridLayout_4.addWidget(self.radioButton_14, 25, 0, 1, 1)
        self.radioButton_23 = QtGui.QRadioButton(self.page_3)
        self.radioButton_23.setObjectName(_fromUtf8("radioButton_23"))
        self.gridLayout_4.addWidget(self.radioButton_23, 16, 0, 1, 1)
        self.radioButton_13 = QtGui.QRadioButton(self.page_3)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.gridLayout_4.addWidget(self.radioButton_13, 24, 0, 1, 1)
        self.radioButton_12 = QtGui.QRadioButton(self.page_3)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.gridLayout_4.addWidget(self.radioButton_12, 23, 0, 1, 1)
        self.radioButton_21 = QtGui.QRadioButton(self.page_3)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.gridLayout_4.addWidget(self.radioButton_21, 14, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 13, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 10, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 11, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 12, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 14, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.page_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 15, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 16, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.page_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 17, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.page_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 18, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.page_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 24, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.page_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 25, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stackedWidget_2.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 1, 0, 1, 6)
        self.stackedWidget.addWidget(self.HookView)
        self.HookCollectionView = QtGui.QWidget()
        self.HookCollectionView.setObjectName(_fromUtf8("HookCollectionView"))
        self.gridLayout_29 = QtGui.QGridLayout(self.HookCollectionView)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.label_101 = QtGui.QLabel(self.HookCollectionView)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_28.addWidget(self.label_101, 0, 4, 1, 1)
        self.mLineEdit_10 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_10.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_10.setObjectName(_fromUtf8("mLineEdit_10"))
        self.gridLayout_28.addWidget(self.mLineEdit_10, 3, 1, 1, 1)
        self.mLineEdit_11 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_11.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_11.setObjectName(_fromUtf8("mLineEdit_11"))
        self.gridLayout_28.addWidget(self.mLineEdit_11, 4, 1, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.HookCollectionView)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_28.addWidget(self.checkBox_11, 4, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.HookCollectionView)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_28.addWidget(self.checkBox_8, 6, 0, 1, 1)
        self.mLineEdit_8 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_8.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_8.setObjectName(_fromUtf8("mLineEdit_8"))
        self.gridLayout_28.addWidget(self.mLineEdit_8, 6, 1, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.HookCollectionView)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_28.addWidget(self.checkBox_9, 2, 0, 1, 1)
        self.mFieldComboBox_6 = QgsFieldComboBox(self.HookCollectionView)
        self.mFieldComboBox_6.setObjectName(_fromUtf8("mFieldComboBox_6"))
        self.gridLayout_28.addWidget(self.mFieldComboBox_6, 2, 4, 1, 1)
        self.label_100 = QtGui.QLabel(self.HookCollectionView)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_28.addWidget(self.label_100, 0, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.HookCollectionView)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout_28.addWidget(self.checkBox_10, 3, 0, 1, 1)
        self.mFieldComboBox_7 = QgsFieldComboBox(self.HookCollectionView)
        self.mFieldComboBox_7.setObjectName(_fromUtf8("mFieldComboBox_7"))
        self.gridLayout_28.addWidget(self.mFieldComboBox_7, 3, 4, 1, 1)
        self.mFieldComboBox_8 = QgsFieldComboBox(self.HookCollectionView)
        self.mFieldComboBox_8.setObjectName(_fromUtf8("mFieldComboBox_8"))
        self.gridLayout_28.addWidget(self.mFieldComboBox_8, 4, 4, 1, 1)
        self.mFieldComboBox_9 = QgsFieldComboBox(self.HookCollectionView)
        self.mFieldComboBox_9.setObjectName(_fromUtf8("mFieldComboBox_9"))
        self.gridLayout_28.addWidget(self.mFieldComboBox_9, 6, 4, 1, 1)
        self.mLineEdit_9 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_9.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_9.setObjectName(_fromUtf8("mLineEdit_9"))
        self.gridLayout_28.addWidget(self.mLineEdit_9, 2, 1, 1, 1)
        self.label_102 = QtGui.QLabel(self.HookCollectionView)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_28.addWidget(self.label_102, 0, 1, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_28, 6, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_29.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.label_103 = QtGui.QLabel(self.HookCollectionView)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_29.addWidget(self.label_103, 2, 1, 1, 1)
        self.label_95 = QtGui.QLabel(self.HookCollectionView)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_29.addWidget(self.label_95, 1, 1, 1, 2)
        self.mFieldComboBox_4 = QgsFieldComboBox(self.HookCollectionView)
        self.mFieldComboBox_4.setObjectName(_fromUtf8("mFieldComboBox_4"))
        self.gridLayout_29.addWidget(self.mFieldComboBox_4, 5, 3, 1, 1)
        self.mLineEdit_2 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_2.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_2.setObjectName(_fromUtf8("mLineEdit_2"))
        self.gridLayout_29.addWidget(self.mLineEdit_2, 2, 3, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.HookCollectionView)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_29.addWidget(self.comboBox_5, 3, 3, 1, 1)
        self.label_96 = QtGui.QLabel(self.HookCollectionView)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_29.addWidget(self.label_96, 4, 1, 1, 2)
        self.mLineEdit_3 = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit_3.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit_3.setObjectName(_fromUtf8("mLineEdit_3"))
        self.gridLayout_29.addWidget(self.mLineEdit_3, 4, 3, 1, 1)
        self.scrollArea_4 = QtGui.QScrollArea(self.HookCollectionView)
        self.scrollArea_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1196, 198))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.pushButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 0, 94, 27))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_13.setGeometry(QtCore.QRect(300, 0, 91, 27))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_29.addWidget(self.scrollArea_4, 7, 2, 1, 2)
        self.mLineEdit = QgsFilterLineEdit(self.HookCollectionView)
        self.mLineEdit.setProperty("qgisRelation", _fromUtf8(""))
        self.mLineEdit.setObjectName(_fromUtf8("mLineEdit"))
        self.gridLayout_29.addWidget(self.mLineEdit, 1, 3, 1, 1)
        self.label_104 = QtGui.QLabel(self.HookCollectionView)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_29.addWidget(self.label_104, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.HookCollectionView)
        self.LivePacketView = QtGui.QWidget()
        self.LivePacketView.setObjectName(_fromUtf8("LivePacketView"))
        self.gridLayout_5 = QtGui.QGridLayout(self.LivePacketView)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(self.LivePacketView)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_5.addWidget(self.frame, 4, 5, 1, 1)
        self.widget = QtGui.QWidget(self.LivePacketView)
        self.widget.setMinimumSize(QtCore.QSize(800, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_31 = QtGui.QLabel(self.widget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_6.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 1, 0, 1, 6)
        self.tabWidget = QtGui.QTabWidget(self.LivePacketView)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Disected = QtGui.QWidget()
        self.Disected.setObjectName(_fromUtf8("Disected"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Disected)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton = QtGui.QPushButton(self.Disected)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_7.addWidget(self.pushButton, 0, 1, 1, 1, QtCore.Qt.AlignBottom)
        self.scrollArea = QtGui.QScrollArea(self.Disected)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1146, 291))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.textBrowser = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_8.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Disected, _fromUtf8(""))
        self.Binary = QtGui.QWidget()
        self.Binary.setObjectName(_fromUtf8("Binary"))
        self.tabWidget.addTab(self.Binary, _fromUtf8(""))
        self.HEX = QtGui.QWidget()
        self.HEX.setObjectName(_fromUtf8("HEX"))
        self.tabWidget.addTab(self.HEX, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 3, 0, 1, 6)
        self.label_28 = QtGui.QLabel(self.LivePacketView)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.LivePacketView)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.LivePacketView)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 0, 2, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.LivePacketView)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_5.addWidget(self.comboBox_2, 0, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.LivePacketView)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 4, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.LivePacketView)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_5.addWidget(self.lineEdit, 0, 5, 1, 1)
        self.frame_2 = QtGui.QFrame(self.LivePacketView)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.widget_3 = QtGui.QWidget(self.frame_2)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 175))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_36 = QtGui.QLabel(self.widget_3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_10.addWidget(self.label_36, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_38 = QtGui.QLabel(self.widget_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.label_39 = QtGui.QLabel(self.widget_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_10.addWidget(self.label_39, 0, 3, 1, 1, QtCore.Qt.AlignTop)
        self.label_37 = QtGui.QLabel(self.widget_3)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_40 = QtGui.QLabel(self.widget_3)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_10.addWidget(self.label_40, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_41 = QtGui.QLabel(self.widget_3)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_10.addWidget(self.label_41, 1, 2, 1, 1, QtCore.Qt.AlignTop)
        self.label_42 = QtGui.QLabel(self.widget_3)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 1, 3, 1, 1, QtCore.Qt.AlignTop)
        self.checkBox = QtGui.QCheckBox(self.widget_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_10.addWidget(self.checkBox, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_3, 1, 0, 2, 1, QtCore.Qt.AlignTop)
        self.pushButton_3 = QtGui.QPushButton(self.frame_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_9.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_9.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.frame_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.formLayout = QtGui.QFormLayout(self.widget_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lineEdit_3 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_43 = QtGui.QLabel(self.widget_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_43)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_44 = QtGui.QLabel(self.widget_2)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_44)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_46 = QtGui.QLabel(self.widget_2)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_47 = QtGui.QLabel(self.widget_2)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_47)
        self.lineEdit_7 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_45 = QtGui.QLabel(self.widget_2)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_45)
        self.line_5 = QtGui.QFrame(self.widget_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_5)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.widget_2)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.buttonBox_2)
        self.line_6 = QtGui.QFrame(self.widget_2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line_6)
        self.gridLayout_9.addWidget(self.widget_2, 1, 2, 2, 1)
        self.label_34 = QtGui.QLabel(self.frame_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_9.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_9.addWidget(self.label_35, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 5, 0, 1, 6)
        self.stackedWidget.addWidget(self.LivePacketView)
        self.PCAP_PackedView = QtGui.QWidget()
        self.PCAP_PackedView.setObjectName(_fromUtf8("PCAP_PackedView"))
        self.gridLayout_27 = QtGui.QGridLayout(self.PCAP_PackedView)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.widget_31 = QtGui.QWidget(self.PCAP_PackedView)
        self.widget_31.setEnabled(True)
        self.widget_31.setObjectName(_fromUtf8("widget_31"))
        self.gridLayout_21 = QtGui.QGridLayout(self.widget_31)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_127 = QtGui.QLabel(self.widget_31)
        self.label_127.setObjectName(_fromUtf8("label_127"))
        self.gridLayout_21.addWidget(self.label_127, 0, 1, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.widget_31)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_21.addWidget(self.lineEdit_16, 0, 2, 1, 1)
        self.tabWidget_3 = QtGui.QTabWidget(self.widget_31)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.Disected_3 = QtGui.QWidget()
        self.Disected_3.setObjectName(_fromUtf8("Disected_3"))
        self.gridLayout_23 = QtGui.QGridLayout(self.Disected_3)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.pushButton_7 = QtGui.QPushButton(self.Disected_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_23.addWidget(self.pushButton_7, 0, 1, 1, 1, QtCore.Qt.AlignBottom)
        self.scrollArea_3 = QtGui.QScrollArea(self.Disected_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1124, 231))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_24 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout_24.addWidget(self.textBrowser_3, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_23.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.Disected_3, _fromUtf8(""))
        self.Binary_3 = QtGui.QWidget()
        self.Binary_3.setObjectName(_fromUtf8("Binary_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.Binary_3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.Binary_3)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout_19.addWidget(self.textBrowser_4, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.Binary_3, _fromUtf8(""))
        self.HEX_3 = QtGui.QWidget()
        self.HEX_3.setObjectName(_fromUtf8("HEX_3"))
        self.tabWidget_3.addTab(self.HEX_3, _fromUtf8(""))
        self.gridLayout_21.addWidget(self.tabWidget_3, 4, 0, 1, 3)
        self.frame_5 = QtGui.QFrame(self.widget_31)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_21.addWidget(self.frame_5, 5, 2, 1, 1)
        self.widget_7 = QtGui.QWidget(self.widget_31)
        self.widget_7.setMinimumSize(QtCore.QSize(800, 0))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_7.setBaseSize(QtCore.QSize(0, 0))
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.gridLayout_22 = QtGui.QGridLayout(self.widget_7)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_122 = QtGui.QLabel(self.widget_7)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout_22.addWidget(self.label_122, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_123 = QtGui.QLabel(self.widget_7)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout_22.addWidget(self.label_123, 1, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.widget_7)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_22.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.buttonBox_5 = QtGui.QDialogButtonBox(self.widget_7)
        self.buttonBox_5.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_5.setObjectName(_fromUtf8("buttonBox_5"))
        self.gridLayout_22.addWidget(self.buttonBox_5, 1, 2, 1, 1)
        self.label_124 = QtGui.QLabel(self.widget_7)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.gridLayout_22.addWidget(self.label_124, 2, 0, 1, 1)
        self.gridLayout_21.addWidget(self.widget_7, 2, 0, 1, 3)
        self.frame_6 = QtGui.QFrame(self.widget_31)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.widget_8 = QtGui.QWidget(self.frame_6)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 175))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_26 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_128 = QtGui.QLabel(self.widget_8)
        self.label_128.setObjectName(_fromUtf8("label_128"))
        self.gridLayout_26.addWidget(self.label_128, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_129 = QtGui.QLabel(self.widget_8)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.gridLayout_26.addWidget(self.label_129, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.label_130 = QtGui.QLabel(self.widget_8)
        self.label_130.setObjectName(_fromUtf8("label_130"))
        self.gridLayout_26.addWidget(self.label_130, 0, 3, 1, 1, QtCore.Qt.AlignTop)
        self.label_131 = QtGui.QLabel(self.widget_8)
        self.label_131.setObjectName(_fromUtf8("label_131"))
        self.gridLayout_26.addWidget(self.label_131, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_132 = QtGui.QLabel(self.widget_8)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.gridLayout_26.addWidget(self.label_132, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_133 = QtGui.QLabel(self.widget_8)
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.gridLayout_26.addWidget(self.label_133, 1, 2, 1, 1, QtCore.Qt.AlignTop)
        self.label_134 = QtGui.QLabel(self.widget_8)
        self.label_134.setObjectName(_fromUtf8("label_134"))
        self.gridLayout_26.addWidget(self.label_134, 1, 3, 1, 1, QtCore.Qt.AlignTop)
        self.checkBox_3 = QtGui.QCheckBox(self.widget_8)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_26.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.widget_8, 1, 0, 2, 1, QtCore.Qt.AlignTop)
        self.pushButton_8 = QtGui.QPushButton(self.frame_6)
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_25.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.frame_6)
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_25.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.widget_9 = QtGui.QWidget(self.frame_6)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.formLayout_3 = QtGui.QFormLayout(self.widget_9)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lineEdit_17 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_135 = QtGui.QLabel(self.widget_9)
        self.label_135.setObjectName(_fromUtf8("label_135"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_135)
        self.lineEdit_18 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_136 = QtGui.QLabel(self.widget_9)
        self.label_136.setObjectName(_fromUtf8("label_136"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_136)
        self.lineEdit_19 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.label_137 = QtGui.QLabel(self.widget_9)
        self.label_137.setObjectName(_fromUtf8("label_137"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_137)
        self.lineEdit_20 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.label_138 = QtGui.QLabel(self.widget_9)
        self.label_138.setObjectName(_fromUtf8("label_138"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_138)
        self.lineEdit_21 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.label_139 = QtGui.QLabel(self.widget_9)
        self.label_139.setObjectName(_fromUtf8("label_139"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_139)
        self.line_17 = QtGui.QFrame(self.widget_9)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_17)
        self.buttonBox_6 = QtGui.QDialogButtonBox(self.widget_9)
        self.buttonBox_6.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_6.setObjectName(_fromUtf8("buttonBox_6"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.buttonBox_6)
        self.line_18 = QtGui.QFrame(self.widget_9)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line_18)
        self.gridLayout_25.addWidget(self.widget_9, 1, 2, 2, 1)
        self.label_140 = QtGui.QLabel(self.frame_6)
        self.label_140.setObjectName(_fromUtf8("label_140"))
        self.gridLayout_25.addWidget(self.label_140, 0, 0, 1, 1)
        self.label_141 = QtGui.QLabel(self.frame_6)
        self.label_141.setObjectName(_fromUtf8("label_141"))
        self.gridLayout_25.addWidget(self.label_141, 0, 2, 1, 1)
        self.gridLayout_21.addWidget(self.frame_6, 6, 0, 1, 3)
        self.buttonBox_7 = QtGui.QDialogButtonBox(self.widget_31)
        self.buttonBox_7.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_7.setObjectName(_fromUtf8("buttonBox_7"))
        self.gridLayout_21.addWidget(self.buttonBox_7, 1, 2, 1, 1)
        self.gridLayout_27.addWidget(self.widget_31, 0, 0, 1, 1)
        self.widget_3.raise_()
        self.tabWidget_3.raise_()
        self.stackedWidget.addWidget(self.PCAP_PackedView)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.HookButton, self.HookCollectionButton)
        MainWindow.setTabOrder(self.HookCollectionButton, self.LivePacketButton)
        MainWindow.setTabOrder(self.LivePacketButton, self.PCAPPacketButton)
        MainWindow.setTabOrder(self.PCAPPacketButton, self.AddHook)
        MainWindow.setTabOrder(self.AddHook, self.EditHook)
        MainWindow.setTabOrder(self.EditHook, self.DeleteHook)
        MainWindow.setTabOrder(self.DeleteHook, self.SearchHook)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.OptionView.setTitle(_translate("MainWindow", "Option View", None))
        self.HookCollectionButton.setText(_translate("MainWindow", "Hook Collection", None))
        self.LivePacketButton.setText(_translate("MainWindow", "Live Packet", None))
        self.PCAPPacketButton.setText(_translate("MainWindow", "Packet from PCAP", None))
        self.HookButton.setText(_translate("MainWindow", "Hook", None))
        self.DeleteHook.setText(_translate("MainWindow", "Delete", None))
        self.EditHook.setText(_translate("MainWindow", "Edit", None))
        self.label.setText(_translate("MainWindow", "Search", None))
        self.AddHook.setText(_translate("MainWindow", "+Hook", None))
        self.radioButton.setText(_translate("MainWindow", "RadioButton", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "Description", None))
        self.label_2.setText(_translate("MainWindow", "Association to Hook Collection", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.label_14.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "Hook", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_5.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_9.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_8.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_11.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_7.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_6.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_17.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_19.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_20.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_18.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_22.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_10.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_15.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_16.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_14.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_23.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_13.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_12.setText(_translate("MainWindow", "RadioButton", None))
        self.radioButton_21.setText(_translate("MainWindow", "RadioButton", None))
        self.label_17.setText(_translate("MainWindow", "TextLabel", None))
        self.label_18.setText(_translate("MainWindow", "TextLabel", None))
        self.label_19.setText(_translate("MainWindow", "TextLabel", None))
        self.label_20.setText(_translate("MainWindow", "TextLabel", None))
        self.label_21.setText(_translate("MainWindow", "TextLabel", None))
        self.label_22.setText(_translate("MainWindow", "TextLabel", None))
        self.label_23.setText(_translate("MainWindow", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow", "TextLabel", None))
        self.label_25.setText(_translate("MainWindow", "TextLabel", None))
        self.label_26.setText(_translate("MainWindow", "TextLabel", None))
        self.label_27.setText(_translate("MainWindow", "TextLabel", None))
        self.label_101.setText(_translate("MainWindow", "Status", None))
        self.checkBox_11.setText(_translate("MainWindow", "Hook 3", None))
        self.checkBox_8.setText(_translate("MainWindow", "Hook 4", None))
        self.checkBox_9.setText(_translate("MainWindow", "Hook 1", None))
        self.label_100.setText(_translate("MainWindow", "Hook", None))
        self.checkBox_10.setText(_translate("MainWindow", "Hook 2", None))
        self.label_102.setText(_translate("MainWindow", "Hook Execution Sequence", None))
        self.label_103.setText(_translate("MainWindow", "Desctiption", None))
        self.label_95.setText(_translate("MainWindow", "Hook Collection Name", None))
        self.label_96.setText(_translate("MainWindow", "Execution Sequence", None))
        self.pushButton_12.setText(_translate("MainWindow", "Save", None))
        self.pushButton_13.setText(_translate("MainWindow", "Cancel", None))
        self.label_104.setText(_translate("MainWindow", "Status", None))
        self.label_31.setText(_translate("MainWindow", "Capture Filter", None))
        self.label_32.setText(_translate("MainWindow", "TextLabel", None))
        self.label_33.setText(_translate("MainWindow", "Packet Area", None))
        self.pushButton.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Disected), _translate("MainWindow", "Dissected", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Binary), _translate("MainWindow", "Binary", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HEX), _translate("MainWindow", "HEX", None))
        self.label_28.setText(_translate("MainWindow", "TextLabel", None))
        self.label_29.setText(_translate("MainWindow", "TextLabel", None))
        self.label_30.setText(_translate("MainWindow", "TextLabel", None))
        self.label_36.setText(_translate("MainWindow", "Field Name", None))
        self.label_38.setText(_translate("MainWindow", "Mark", None))
        self.label_39.setText(_translate("MainWindow", "Display Format", None))
        self.label_37.setText(_translate("MainWindow", "Value", None))
        self.label_40.setText(_translate("MainWindow", "TextLabel", None))
        self.label_41.setText(_translate("MainWindow", "TextLabel", None))
        self.label_42.setText(_translate("MainWindow", "TextLabel", None))
        self.checkBox.setText(_translate("MainWindow", "CheckBox", None))
        self.pushButton_3.setText(_translate("MainWindow", "-", None))
        self.pushButton_2.setText(_translate("MainWindow", "+", None))
        self.label_43.setText(_translate("MainWindow", "Selected Field Name", None))
        self.label_44.setText(_translate("MainWindow", "Expected Return Type", None))
        self.label_46.setText(_translate("MainWindow", "Minimun", None))
        self.label_47.setText(_translate("MainWindow", "Maximun", None))
        self.label_45.setText(_translate("MainWindow", "Selected Packet Name", None))
        self.label_34.setText(_translate("MainWindow", "Field Area", None))
        self.label_35.setText(_translate("MainWindow", "Fuzzing Area", None))
        self.label_127.setText(_translate("MainWindow", "PCAP File", None))
        self.pushButton_7.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Disected_3), _translate("MainWindow", "Dissected", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Binary_3), _translate("MainWindow", "Binary", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.HEX_3), _translate("MainWindow", "HEX", None))
        self.label_122.setText(_translate("MainWindow", "Capture Filter", None))
        self.label_123.setText(_translate("MainWindow", "TextLabel", None))
        self.label_124.setText(_translate("MainWindow", "Packet Area", None))
        self.label_128.setText(_translate("MainWindow", "Field Name", None))
        self.label_129.setText(_translate("MainWindow", "Mark", None))
        self.label_130.setText(_translate("MainWindow", "Display Format", None))
        self.label_131.setText(_translate("MainWindow", "Value", None))
        self.label_132.setText(_translate("MainWindow", "TextLabel", None))
        self.label_133.setText(_translate("MainWindow", "TextLabel", None))
        self.label_134.setText(_translate("MainWindow", "TextLabel", None))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox", None))
        self.pushButton_8.setText(_translate("MainWindow", "-", None))
        self.pushButton_9.setText(_translate("MainWindow", "+", None))
        self.label_135.setText(_translate("MainWindow", "Selected Field Name", None))
        self.label_136.setText(_translate("MainWindow", "Expected Return Type", None))
        self.label_137.setText(_translate("MainWindow", "Minimun", None))
        self.label_138.setText(_translate("MainWindow", "Maximun", None))
        self.label_139.setText(_translate("MainWindow", "Selected Packet Name", None))
        self.label_140.setText(_translate("MainWindow", "Field Area", None))
        self.label_141.setText(_translate("MainWindow", "Fuzzing Area", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

from qgsfieldcombobox import QgsFieldComboBox
from qgsfilterlineedit import QgsFilterLineEdit
